spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: springbootapp.email.from@gmail.com
    password: zoxtppbktwtrmrly
#    pwd:Spring@123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true